### ISSUE TITLE
You might also be interested in...

### ISSUE THREAD

**Issue by i-make-robots** [antonvh/L3onardo-plotter#1]
https://github.com/marginallyclever/makelangelo-software, which has several styles of image conversion and pattern generation, all of which could be saved to CSV for your machine.

I used to have a style like this that applied a Traveling Salesman style solver to find shortest route.  Now I dump points into a grid of buckets and sort each bucket by nearest-neighbor.

Thanks for sharing!

**Comment by antonvh** [comment]
Nice, thanks!
